### PR TITLE
Bit of cleanup in wm.py

### PR DESCRIPTION
**Pull request by rdbende**

### CODE REVIEW

**Comment by rdbende** [comment]
Also add Idared

**Comment by rdbende** [comment]
And taskbar progressbar thingy for Windows

**Comment by Moosems** [comment]
Quick question, what's the difference between using the tuple and the curly braces?

**Comment by rdbende** [comment]
The "curly braces" are called [sets](https://realpython.com/python-sets). In these situations, I think it makes more sense to use a set, because we're only interested in whether or not the value is an element of it. However I figured, that using tuples is faster (by a very little, only noticable at 1000000 runs), and since tuples are immutable, they also take up less space (it's garbage collected immediately, so doesn't really matter).

**Pull request merged**
