### PR TITLE
Fix a lotta bugs, add some tests

### PR DESCRIPTION
**Pull request by rdbende**
I won't describe all the things I've done

### CODE REVIEW

**Comment by Moosems** [comment]
oh my goodness

**Comment by Moosems** [comment]
Ever heard of condensation? I've gotten 10 emails in the past 5 minutes with all the commits lol

**Comment by rdbende** [comment]
> Ever heard of condensation? I've gotten 10 emails in the past 5 minutes with all the commits lol

I'm testing some pytest on github actions, and I need update something after each run. You can unsubscribe from this PR in the panel on the right :)

**Comment by Moosems** [comment]
No, it's fine I just thought i might take the chance to mess with you a little :)

**Comment by sumeshir26** [comment]
image
How did you manage to make this happen? 😂

**Comment by sumeshir26** [comment]
Never mind its from the removing of tkdnd

**Comment by Moosems** [comment]
Lol

**Comment by im-coder-lg** [comment]
> I won't describe all the things I've done
@rdbende from the description

Yeah bro you can even say the commits speak for itself like Hans Niemann said for his (rather stupid, reasonless, and costly) $400m lawsuit. ("My lawsuit speaks for itself" - Hans)

**Comment by im-coder-lg** [comment]
Oh dear the branch name 😂

**Comment by rdbende** [comment]
> image How did you manage to make this happen? :joy:

Yupp. Eight thousand lines of Tcl code removed. I hope I can reduce that by rewriting the Tcl part in Python, while making it more maintainable (I love how much more readable Serif has become, when I translated it to Python).

**Comment by im-coder-lg** [comment]
Well, now what?

Wait is Tukaan in a bit of a usable stage? Asking for a (secret tba) project of mine.

**Comment by rdbende** [comment]
Yes, Tukaan is already in usable state and you can use it to build application, however some features are still missing, and there might be bugs that I haven't discovered. Documentation is also missing as it's not a priority atm, but you can probably figure out things from the source code. Altogether, I recommend you to wait until the next release, 'cause a **LOT OF** thing will change, but then I'd be happy to see people use it and give feedback on how usable it is.

> And @rdbende try using commitizen.

Tbh, I'm happy with my commit messages, they are really descriptive, lolz

**Pull request merged**
