### PR TITLE
Add Gtk theming

### PR DESCRIPTION
**Pull request by rdbende**
# Gtk themes for Tukaan

## Basics
```python
from tukaan.themes import GtkTheme

app.theme = GtkTheme  # Native Gtk theme

app.theme = GtkTheme("Adwaita")  # Select which Gtk theme to use
```

## Even more stuff
```python
>>> from tukaan.themes import GtkTheme

>>> print(GtkTheme.themes)  # Returns the Gtk themes available on the system
['Adwaita', 'Breeze', 'Breeze-Dark', 'Dracula', 'Raleigh', 'Yaru-dark', 'Yaru-light']

>>> print(GtkTheme.system_theme)  # Get the system's active Gtk theme
'Yaru-dark'
```

### CODE REVIEW

**Comment by rdbende** [comment]
TODO:
- [ ] Translate Tcl scripts to Python (like for Serif)
- [ ] Make `_use` work on class as well as on instance
- [ ] `get_themes()` -> `classproperty(themes)`
- [ ] `get_system_theme()` -> `classproperty(system_theme)`

**Comment by rdbende** [comment]
> What happened to Snack? I was reallay looking forward to it :(

Yeah, I scrapped it, 'cause I have a better idea: let's not put the sound stuff inside Tukaan, instead make an official audio handling / software synth module dedicated to Tukaan, written from scratch. `Filomeel` (toucan -> `tukaan`, philomela [nightingale] -> `filomeel` lol) is a private repository yet, so you can't see it, but I have some kind of development going on in it.

**Comment by sumeshir26** [comment]
nice :) looking forward to it

**Comment by rdbende** [comment]
After all, I might drop Gtk theme support. At least in the Tukaan core.
Gtk 2 is not reached its end of life, and while Gtk 2 themes still exist, using obsolete stuff is usually not a good idea.

**Comment by sumeshir26** [comment]
So GTK is dropped?

**Comment by rdbende** [comment]
For Tukaan yes. You can see the reasoning above.

I still develop it though: https://github.com/Geballin/gtkTtk/pulls xdd

**Comment by im-coder-lg** [comment]
Well, why is it dropped? To me, it looks like the biggest chance to make a proper Python app for Linux easily. How about KDE theming too if possible?

**Comment by Moosems** [comment]
Cause development for GTK has been dropped. No use

**Comment by rdbende** [comment]
> Well, why is it dropped?

Because GTK 3 and 4 uses CSS for theming (at least if theming is an appropriate term in case of GTK 4), and GTK 2 officially reached its end of life.

TileGTK (the stuff this PR is about) uses GTK 2 pixmaps and renders them to a Tk drawable. And while GTK 2 themes still exist, it's not a good idea to implement a new feature using obsolete APIs.

Once CSS theming is added, we can try to do something with GTK themes, but it's definitely not an easy thing to implement.

> How about KDE theming too if possible?

FYI: Tukaan already has that.

It uses a nice theme with the system color scheme on KDE Plasma 5 and above. For me, KDE integration is one of the most important features, as I use Plasma.

Once (in the mid-2000s) there was also an extension called Tile-Qt which made it possible to use Qt themes inside Tk, and thus make it look native on Plasma. I'm almost certain that this couldn't be done with the newest versions of Qt.

**Comment by im-coder-lg** [comment]
Why is the same comment repeated? Looks sus to me. Eyes on you, GitHub.

I see. Let's just hope CSS is supported on Python. Last time I heard of it, it was used on websites.

**Comment by rdbende** [comment]
> Why is the same comment repeated?

Is it?

> Let's just hope CSS is supported on Python.

There's already a basic CSS parser in #71, so that isn't a problem. The harder thing is to actually draw the theme based on it ://

**Comment by Moosems** [comment]
I don't see a duplicate comment. How exactly does Tk take in a theme? Could you not dynamically edit a ttk theme using css?

**Comment by rdbende** [comment]
> Could you not dynamically edit a ttk theme using css?

You can. The tricky thing in it is to dynamically edit the tile images that make up the theme. [`ttkbootstrap`](https://github.com/israel-dryer/ttkbootstrap) does this by using PIL, but my idea is that if Tukaan supported SVG images, we could create them on the fly and they could even have rounded corners, antialiasing, and they would be **scalable**.
Back when I made the Azure theme, I had the same idea, only with Base64 image data. Turns out, it's not at all simple to work with Base64 encoded PNG images, so I gave up XDD

**Comment by sumeshir26** [comment]
What if you turn each wiget into a `Canvas` so you can style it in basicallay any way like CustomTkinter?

**Comment by rdbende** [comment]
Then it would be just as buggy and slow as CustomTkinter. Or slower. I really don't want that.

#121 adds a `Canvas` widget that has the ability to draw onto a in-memory surface, and copy the drawing to a Tk image. My plan is to create another theming engine in addition to the SVG-based one, using this feature of the canvas widget.

**Pull request closed without merging**
