### PR TITLE
Errors     :D

### PR DESCRIPTION
**Pull request by TheRealPenguin12**
I gave basic errors, you can edit them to your specifications.

- Des

### CODE REVIEW

**Review by Moosems — COMMENTED** [review]
I like this a lot but will leave @rdbende to give final approval. I think it would be nice if you could give some broken code that raises an error so I can understand it better

**Review by Moosems — APPROVED** [review]
I like it

**Comment by desvasicek** [comment]
Thanks

**Comment by desvasicek** [comment]
```python
app1 = App()
app2 = App()
app1.run()
app2.run()
```
```yaml
Traceback (most recent call last):
   File "/file/path/", line 5, in <module>
    app2 = App()
AppError: can't create multiple App instances. Use tukaan.Window instead.
```

**Comment by desvasicek** [comment]
Please note this is only skeleton code: if you like it, you can keep it, if you don't, you don't have to, or you can make the final edits.

**Comment by Moosems** [comment]
> ```python
> app1 = App()
> app2 = App()
> app1.run()
> app2.run()
> ```
> 
> ```yaml
> Traceback (most recent call last):
>    File "/file/path/", line 5, in <module>
>     app2 = App()
> AppError: can't create multiple App instances. Use tukaan.Window instead.
> ```

Looks perfect!

**Comment by rdbende** [comment]
Honestly, I don't see the point of this PR.
Since I'm using custom error messages everywhere in the code, there's no need for these defaults. The example just confirms this, these defaults have nothing to do with this example error.

> ```python
> app1 = App()
> app2 = App()
> ```
> 
> ```yaml
> Traceback (most recent call last):
>    File "/file/path/", line 5, in <module>
>     app2 = App()
> AppError: can't create multiple App instances. Use tukaan.Window instead.
> ```

https://github.com/tukaan/tukaan/blob/5e25f488dd4f3960c2ff385fbb8c0a10eb31bf9a/tukaan/app.py#L25

**Comment by im-coder-lg** [comment]
Perhaps dig for more errors and add those here?

**Pull request closed without merging**
