### PR TITLE
packaging: migrate to a setup.cfg build

### PR DESCRIPTION
**Pull request by demberto**
TkDND is quite a big dependency which actually needs to be platform specific to reduce the size of the distribution wheels. I think you should move them to `libtukaan`.

The other option is you keep them in tukaan, but then to reduce the distribution size, we need to fallback to `setup.py` based packaging.

### CODE REVIEW

**Comment by Moosems** [comment]
Interesting thought. I'll leave this up to rdbende

**Comment by Agent-Hellboy** [comment]
I check out this pull request as there was no setup.py I created one and called setup() inside it and then after installing (`python3-pil python3-pil.imagetk`)  I was able to install it but I am still not able to use the package 
getting this error 
```
File "/home/proshan/.local/lib/python3.8/site-packages/libtukaan/serif.py", line 16, in Serif
    loaded_fonts: list[Path] = []
TypeError: 'type' object is not subscriptable
```
I am installing it as `python3 setup.py install`
have you tested the install process?

**Comment by rdbende** [comment]
> That's because @demberto removed setup.py. I'll request it to be added again

No, that's my fault. I forgot to put a `from __future__ import annotations` statement to the top of `serif.py`. I'm surprised though, that `list[Path]` works on Py39 without a future statement.

**Comment by Agent-Hellboy** [comment]
Have you guys checked the latest release? I don't think dependencies are getting installed properly?

Do we have written  unittests?

I have help with unittest if you want?maybe setting up the release pipeline.

**Comment by rdbende** [comment]
> Have you guys checked the latest release? I don't think dependencies are getting installed properly?

It worked for me (Debian Bullseye, Py39) and for @Moosems as well (macOS, Py310)

> Do we have written unittests?

No 😕. See #3

**Comment by Agent-Hellboy** [comment]
Okay, I will try to help with writing the unit test.

**Comment by demberto** [comment]
> I'm surprised though, that `list[Path]` works on Py39 without a future statement.

Python 3.9 updated the syntax for many type hints. The older alternatives are deprecated in 3.9+ now.

**Comment by rdbende** [comment]
I thought it was only Python 3.10

**Comment by demberto** [comment]
> I check out this pull request as there was no setup.py

setup.cfg builds use the `build` command line tool to create bdist and sdist wheels. On my tests it worked perfectly under a 3.10 venv on Windows

**Comment by Moosems** [comment]
> > I'm surprised though, that `list[Path]` works on Py39 without a future statement.
> 
> Python 3.9 updated the syntax for many type hints. The older alternatives are deprecated in 3.9+ now.

Well using `foo: int = 5`still works

**Comment by rdbende** [comment]
> Well using `foo: int = 5`still works

Coz' that's already the new syntax.

**Comment by demberto** [comment]
> Well using `foo: int = 5`still works

Yes. Not all type hints were updated. Actually one can call it streamlined. The builtins are useable as type hints themselves now

**Comment by demberto** [comment]
@rdbende what have you thought about putting tkdnd in libtukaan?

**Comment by rdbende** [comment]
> @rdbende what have you thought about putting tkdnd in libtukaan?

See #88

**Comment by Agent-Hellboy** [comment]
I don't think we should raise these error after successful installation.
```
RuntimeError: Tcl/Tk for Python is not installed on your system.
              Please install the `python3-tk` package with your package manager.
 ```
 check this for this can we avoided 
 https://stackoverflow.com/questions/71757486/an-elegant-means-of-installing-apt-packages-within-a-setuptools-setup-py-file

**Comment by rdbende** [comment]
> check this, for this, can be avoided

True, but then the hard thing would to detect the package manager based on the distro, and also the package names (for example it's not `python3-tk` on Arch)

**Comment by Agent-Hellboy** [comment]
>>>True, but then the hard thing would to detect the package manager based on the distro, and also the package names (for example it's not python3-tk on Arch)
I can understand but everything comes down to user experience, I am suggesting using this at a later point in time.

**Comment by Moosems** [comment]
> Yes. Not all type hints were updated. Actually one can call it streamlined. The builtins are useable as type hints themselves now


Oh really? So that would break in python 3.8?

**Comment by demberto** [comment]
> Oh really? So that would break in python 3.8?

```py
from __future__ import annotations

import collections

# ❌ Fails on Python >3.9
a = collections.defaultdict[str, int](int)

# ✔ Works on Python >3.9
a: collections.defaultdict[str, int] = collections.defaultdict(int)
```

This feature is introduced via [PEP 585](https://peps.python.org/pep-0585).

**Comment by Moosems** [comment]
```python
# ✔ Works on Python >3.9
a: collections.defaultdict[str, int] = collections.defaultdict(int)
```

And this is backwards compatible?

**Comment by demberto** [comment]
> ```python
> # ✔ Works on Python >3.9
> a: collections.defaultdict[str, int] = collections.defaultdict(int)
> ```
> 
> And this is backwards compatible?

My bad I missed the symbols, the shorter syntax is for Python 3.9+, the older syntax works perfectly but is deprecated. It wont be removed anytime soon

**Comment by rdbende** [comment]
#110 Removes TkDnD from here, so I'm closing this

**Pull request closed without merging**
