### PR TITLE
Add theming

### LINKED ISSUE #62: Feature: Theming
TODO:

- [ ] Apply native theme
      Would be nice to use [tile-gtk](https://github.com/rdbende/gttk) (and tile-qt) on Linux, though I can't release binaries here, as Gtk is LGPL
- [ ] Get current theme
- [ ] Set theme
- [ ] Get available themes

### PR DESCRIPTION
**Pull request by rdbende**
Hopefully the final attempt at implementing theming

### CODE REVIEW

**Comment by Moosems** [comment]
How could I change my theming?

**Comment by rdbende** [comment]
Actually it's pretty straightforward. You can assign any class or object that inherits from `tukaan.Theme` to `App.theme`, and that's it.

https://github.com/tukaan/tukaan/blob/2c1de2fa34ff04827bc0f593e6857c4be2c79bd3/tukaan/app.py#L79-L81

**Comment by Moosems** [comment]
So I just import the theme and use the `app.theme(theme)` method?

**Comment by rdbende** [comment]
`app.theme = theme` because it's a property, but yes.

**Comment by Moosems** [comment]
Oh 🤦

**Comment by Moosems** [comment]
Works just fine for me!

**Comment by Moosems** [comment]
Oooooooo

**Comment by rdbende** [comment]
On MS Windoze the shadow is still missing from the tooltip, but in the future it could be implemented with something like this (preferably at C++ level):

```py
import tkinter as tk
import ctypes

GetWindowLongA = ctypes.windll.user32.GetWindowLongPtrA
SetWindowLongA = ctypes.windll.user32.SetWindowLongPtrA
CallWindowProcW = ctypes.windll.user32.CallWindowProcW
DwmExtendFrameIntoClientArea = ctypes.windll.dwmapi.DwmExtendFrameIntoClientArea

WM_NCCALCSIZE = 0x0083
WS_POPUP = 0x80000000
WS_THICKFRAME = 0x00040000
GWL_WNDPROC = -4
GWL_STYLE = -16

class Margins(ctypes.Structure):
    _fields_ = [
        ("cxLeftWidth", ctypes.c_int),
        ("cxRightWidth", ctypes.c_int),
        ("cyTopHeight", ctypes.c_int),
        ("cyBottomHeight", ctypes.c_int),
    ]

root = tk.Tk()
root.update_idletasks()
hwnd = int(root.wm_frame(), 16)

borderless = Margins(1, 1, 1, 1)
DwmExtendFrameIntoClientArea(hwnd, ctypes.byref(borderless))

@ctypes.WINFUNCTYPE(*(ctypes.c_uint64,) * 5)
def wndproc(hWnd, uMsg, wParam, lParam):
    if uMsg == WM_NCCALCSIZE:
        return 0
    return CallWindowProcW(*map(ctypes.c_uint64, (old_wndproc, hWnd, uMsg, wParam, lParam)))

old_wndproc = GetWindowLongA(hwnd, GWL_WNDPROC)

SetWindowLongA(hwnd, GWL_WNDPROC, wndproc)
SetWindowLongA(hwnd, GWL_STYLE, GetWindowLongA(hwnd, GWL_STYLE) | WS_POPUP)

root.mainloop()
```

**Pull request merged**
