### PR TITLE
Add Mica effect, titlebar customization

### PR DESCRIPTION
**Pull request by rdbende**
Hi!

Could someone with Windows 11 build 22000 or above test the following two snippets for me?

I don't have this build, and installing a new Windows build is kinda pain, so I'd be really grateful, if you someone could test them, and give feedback. Thanks!

You can just download the `2022-02-16` branch, and run this two code to test it.

### Mica

This code should add a Mica effect to the window, and remove it after 10 seconds.
```python
import tukaan

app = tukaan.App(title="Test titlebar and window border customization")

app.set_backdrop_effect("mica")

tukaan.Timeout(10, lambda: app.set_backdrop_effect(None)).start()

app.run()

```

### Titlebar bg, fg and window border:
```python
import tukaan

app = tukaan.App(title="Test titlebar and window border customization")

app.Titlebar.bg_color = tukaan.Color("#ffc568")
app.Titlebar.fg_color = tukaan.Color("#6667ab")
app.border_color = tukaan.Color("#007fff")

app.run()
```
I'm not sure, if I implemented the bg, fg and border color functions correctly, and the colors may be something completely else. Here's how they should look:
 asdf | color
--- | ---
titlebar should be this color | ffc568
titlebar text should be this color | 6667ab
window border should be this color | 007fff

### CODE REVIEW

**Comment by sumeshir26** [comment]
I will 100% test this, but proballay not until tuseday night since im going out of town without my pc

**Comment by im-coder-lg** [comment]
Can't you take it with you?

**Comment by im-coder-lg** [comment]
That's what I do when I go to my hometown, it's really ez to code with that.

**Comment by rdbende** [comment]
> I will 100% test this, but proballay not until tuseday night since im going out of town without my pc

Thanks @sumeshir26 !

**Comment by sumeshir26** [comment]
Well, that got fixed by changing line 18 of __init__.py to `from .window import App, Window`

**Comment by rdbende** [comment]
Now they should work!

**Comment by sumeshir26** [comment]
@rdbende Now this:
image

**Comment by rdbende** [comment]
Fixed.
Lol, I can't even copy-paste my code 🙄😝. But if you got to `border_color` it means that the rest works 👍

**Review by sumeshir26 — APPROVED** [review]
Works!

**Comment by rdbende** [comment]
> Works!

Hurray! That's nice! Thanks for the testing!

**Pull request merged**
